version: '3.8'

services: 
  db:
    image: postgres:15-alpine
    container_name: gestao_projetos_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "dev%RDXxdr%"
      POSTGRES_DB: gestao_projetos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: